### ISSUE TITLE
Dungeon waypoint should be variable (z-axis)

### ISSUE THREAD

**Issue by Kezuino** [EvoluniaCommunity/OTClientV8-Modules#2]
The z-axis for dungeons is variable. So loading a static waypoint file is not the right solution when dealing with waypoints for dungeon as they don't always work. 
  
  Dungeons are located on different levels (same map) and your character is transported to the first available map, which makes the z-axis variable.
  
  Proposal:
  When dealing with waypoints for dungeon, only allow to actually load these waypoints when the player is in the dungeon. This way the waypoints can be loaded using the player z-index as base for the waypoints.
  
![levelsdungeon](https://user-images.githubusercontent.com/9204327/150020885-8dd970c2-83b9-4a59-ac5a-b45eaabf593a.gif)

**Comment by EvoluniaCommunity** [comment]
This is a great idea. I already have an idea how this could work. I'll test some things out!

**Comment by EvoluniaCommunity** [comment]
Started work on this in latest commit.

https://github.com/EvoluniaCommunity/OTClientV8-Modules/commit/adb322f165daf2dec525b2cfe26670affb925028

**Comment by EvoluniaCommunity** [comment]
Since the configs are loaded when the CaveBot is first turned on, we will need to edit the config loading function in Cave's Main to take into account the position of the player, or possibly load configs based on position, changing when the player moves locations.

**Comment by EvoluniaCommunity** [comment]
This commit: https://github.com/EvoluniaCommunity/OTClientV8-Modules/commit/a34490574853003825d6d1364a8525ea332bd0b4 includes a partially working auto-dungeon system. Still some work to be done, but auto-loading of waypoint based on floor level is complete, using onPlayerPositionChange() in the main cavebot file.

**Comment by EvoluniaCommunity** [comment]
The newest commit in v2.2.0: https://github.com/EvoluniaCommunity/OTClientV8-Modules/commit/37d6928cfab65e3a991aa4d1bafc7aa6eddbf3eb fixes some issues on waypoint loading and separates dungeon waypoint loading and normal waypoint loading. This also fixes the slow script in Cave/Main.lua where onPlayerPositionChange() and the config is loaded on every new position. Instead, they are loaded seperately, and normal waypoints are loaded when the macro is turned on/off or the player logged into the game. Lastly, CaveBot Recorder works again.

---

On another note, this introduces the Libraries class (which will be populated as time goes on). More information to come soon.
