### ISSUE TITLE
mana() won't work properly when using !percentage

### ISSUE THREAD

**Issue by Kezuino** [EvoluniaCommunity/OTClientV8-Modules#4]
To correctly display health/mana and since the protocol limits the health and mana to be 65535 at maximum (uint16), some players use !percentage to display health/mana in percentages instead of values. This does however also affect the current health, current mana ,max health and max mana to be in percentages instead of the actual value. This also means that mana() will return the current mana in percentages and calculating cost will no longer work properly.

https://github.com/EvoluniaCommunity/OTClientV8-Modules/blob/62460fda8ebeb98408b0cab49815a949fd969330/game_bot/default_configs/WoofTools/Core/Heals/Heals.Conditions.lua#L188

**Comment by EvoluniaCommunity** [comment]
Removed the conditions manager for now. It seems with this issue, it'll cause the client to slowly lag more and more until it's nearly unusable, causing deaths in cavebot. -- Will look for a fix.

**Comment by EvoluniaCommunity** [comment]
I figured the easiest / safest route here is to remove the check for mana since it's negligible in Evolunia. 

It's running this way on the 2.2.0 branch currently.
--
A separate issue with this same tool is the isBurning() portion, which throws errors in the console if looking for the condition.

**Comment by EvoluniaCommunity** [comment]
Fixed in v2.2.0
